export const actionsEnums = {
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  MEMBER_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED',
  UPDATE_FILTER: 'UPDATE_FILTER',
  MEMBER_EDIT: 'MEMBER_EDIT',
  MEMBER_EDIT_COMPLETED: 'MEMBER_EDIT_COMPLETED',
}
